/*
 * Copyright 2018 Zhenjie Yan
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.hcs.android.processor.constant;


public interface Constants {
    String DOC_EDIT_WARN = "This file was generated by HCS automatically and you should NOT edit it.";
    String PACKAGE_NAME = "com.hcs.android";
    String STRING_UTIL_TYPE = PACKAGE_NAME + ".common.util.StringUtil";
    String COMMAND_MANAGER_PACKAGE = PACKAGE_NAME + ".annotation.api";
    String COMMAND_MANAGER_TYPE = COMMAND_MANAGER_PACKAGE + ".ICommandManager";
    String HANDLER_TYPE = PACKAGE_NAME + ".annotation.api.IHandler";
}